### PR TITLE
new template - YAML documents should contain a required key

### PR DESCRIPTION
**Pull request by andmagom**
### **New Template**

Hello, I'm Andres from Colombia. 
I work in a enterprise where we are going to use yaml plugin in order to validate some yaml files inside software projects. I have created a new template that I want to share you.

Sometimes we need that a specific yaml file contains some required key, perhaps because it is a good coding practice. 
To instance, Look this kubernetes yaml file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```
This yaml could be better if it contains the readinessProbe and livenessProbe keys, because they guarantees stability for our microservices. So, this new template could validate that keys exists in that file.
This template require 3 parameters:
- **key-name**: Key name: e.g: kind
- **value-key**: Value for key: e.g: Deployment
- **required-key**: Required key. e.g: readinessProbe

**The key-name and value-key parameters are required because not all yaml files must to have the required-key, so it will filter yaml files.**

So, I have created this template that I hope other people can use it.
I'm going to attent some question that you could to have.
Have a nice day,

### CODE REVIEW

**Comment by andmagom** [comment]
Do you know what is wrong with travis ?

**Comment by sbaudoin** [comment]
Hello,

Yes: the problem comes from the deprecation of Oracle's Java 8 Docker image. I switched to openjdk8 and it works: you might rebase and try again but don't bother I'm going to validate your PR and the build will happen eventually.

**Comment by sbaudoin** [comment]
Build passed ;)

**Comment by andmagom** [comment]
Thanks =)

**Pull request merged**
